// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjLawFWC37V-RYDtMMUeTrg9sSNPOxLRg',
    appId: '1:703213714738:web:b48265baf96d6b1739eb2b',
    messagingSenderId: '703213714738',
    projectId: 'task-management-3e9a8',
    authDomain: 'task-management-3e9a8.firebaseapp.com',
    storageBucket: 'task-management-3e9a8.firebasestorage.app',
    measurementId: 'G-5V7ESVR75D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC-txfCuEGoYv6pClpCKJKqdVjlvEvaXk',
    appId: '1:703213714738:android:f2a1f71dc1f3883039eb2b',
    messagingSenderId: '703213714738',
    projectId: 'task-management-3e9a8',
    storageBucket: 'task-management-3e9a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-M5q5nHO8ubmt6W5KOAE1wGwMkl5QFcU',
    appId: '1:703213714738:ios:576c29e4cee7d3ae39eb2b',
    messagingSenderId: '703213714738',
    projectId: 'task-management-3e9a8',
    storageBucket: 'task-management-3e9a8.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-M5q5nHO8ubmt6W5KOAE1wGwMkl5QFcU',
    appId: '1:703213714738:ios:576c29e4cee7d3ae39eb2b',
    messagingSenderId: '703213714738',
    projectId: 'task-management-3e9a8',
    storageBucket: 'task-management-3e9a8.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjLawFWC37V-RYDtMMUeTrg9sSNPOxLRg',
    appId: '1:703213714738:web:28bc3b805420a95439eb2b',
    messagingSenderId: '703213714738',
    projectId: 'task-management-3e9a8',
    authDomain: 'task-management-3e9a8.firebaseapp.com',
    storageBucket: 'task-management-3e9a8.firebasestorage.app',
    measurementId: 'G-H3VHDYMJXY',
  );
}
